# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'command_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommand_service.proto\x12\x0f\x63ommand_service\"d\n\x0e\x43ommandRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x08packMode\x18\x02 \x01(\x0e\x32\x19.command_service.PackMode\x12\x0b\n\x03req\x18\x03 \x01(\x0c\x12\x0c\n\x04path\x18\x04 \x01(\t\"W\n\x0f\x43ommandResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x08packMode\x18\x02 \x01(\x0e\x32\x19.command_service.PackMode\x12\x0b\n\x03res\x18\x03 \x01(\x0c*5\n\x08PackMode\x12\x12\n\x0ePACK_MODE_JSON\x10\x00\x12\x15\n\x11PACK_MODE_MSGPACK\x10\x01\x32h\n\x0e\x43ommandService\x12V\n\rCommandStream\x12\x1f.command_service.CommandRequest\x1a .command_service.CommandResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKMODE']._serialized_start=233
  _globals['_PACKMODE']._serialized_end=286
  _globals['_COMMANDREQUEST']._serialized_start=42
  _globals['_COMMANDREQUEST']._serialized_end=142
  _globals['_COMMANDRESPONSE']._serialized_start=144
  _globals['_COMMANDRESPONSE']._serialized_end=231
  _globals['_COMMANDSERVICE']._serialized_start=288
  _globals['_COMMANDSERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
